/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JPanel;

/**
 *
 * @author Alejandro
 */
public class MonsterView extends javax.swing.JPanel {

    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    public void setMonster(NapakalakiGame.Monster m) {
        monsterModel = m;
        name.setText(m.getName());
        combatLevel.setText(Integer.toString(m.getCombatLevel()));
        levelChangeAgainstCultistPlayer.setText(Integer.toString(m.getCombatLevelAgainstCultistPlayer()));
        this.fillBCPanel(badConsequence,m.getBadConsequence());
        priceView1.SetPrice(m.getPrize());
        repaint();
    }

    private void fillBCPanel(JPanel aPanel, NapakalakiGame.BadConsequence bc) {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();

        if (bc.getClass().getSimpleName().equals("NumericBadConsequence")) {
            NumericBadConsequenceView aNBCView = new NumericBadConsequenceView();
            aNBCView.setBadConsequence(bc);
            aNBCView.setVisible(true);
            aPanel.add(aNBCView);
        } else if (bc.getClass().getSimpleName().equals("SpecificBadConsequence")) {
            SpecificBadConsequenceView aSBCView = new SpecificBadConsequenceView();
            aSBCView.setBadConsequence(bc);
            aSBCView.setVisible(true);
            aPanel.add(aSBCView);
        } else if (bc.getClass().getSimpleName().equals("DeathBadConsequence")) {        
            DeathBadConsequenceView aDBCView = new DeathBadConsequenceView();
            aDBCView.setBadConsequence(bc);
            aDBCView.setVisible(true);
            aPanel.add(aDBCView);
        }

        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        levelChangeAgainstCultistPlayer = new javax.swing.JLabel();
        badConsequence = new javax.swing.JPanel();
        priceView1 = new GUI.PriceView();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        name.setText("name");

        combatLevel.setText("combatLevel");

        levelChangeAgainstCultistPlayer.setText("levelChangeAgainstCultistPlayer");

        badConsequence.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Name");

        jLabel2.setText("Combat Level");

        jLabel3.setText("Level Change Against Cultist Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(name))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(combatLevel))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(levelChangeAgainstCultistPlayer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combatLevel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelChangeAgainstCultistPlayer)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(badConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel badConsequence;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel levelChangeAgainstCultistPlayer;
    private javax.swing.JLabel name;
    private GUI.PriceView priceView1;
    // End of variables declaration//GEN-END:variables

    private NapakalakiGame.Monster monsterModel = null;
}
