/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author nestor
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    public void setNapakalaki(NapakalakiGame.Napakalaki n) {
        napakalakiModel = n;
        monsterView1.setVisible(false);
        monsterView1.setMonster(n.getCurrentMonster());
        playerView1.setPlayer(n.getCurrentPlayer());
        playerView1.setNapakalakiModel(n);
        playerView1.ocultarStealTreasure();
        if (meet == false) {
            Combat.setVisible(false);
            NextTurn.setVisible(false);
        } else if (combat == false) {
            playerView1.ocultarMakeVisible();
            MeetTheMonster.setVisible(false);
            NextTurn.setVisible(false);
            Combat.setVisible(true);
        } else {
            playerView1.mostrarMakeVisible();
            if (playerView1.getModel().canISteal()) {
                playerView1.mostrarStealTreasure();
            } else {
                playerView1.ocultarStealTreasure();
            }
            Combat.setVisible(false);
            monsterView1.setVisible(true);
            NextTurn.setVisible(true);
        }
        if (nextTurn) {
            MeetTheMonster.setVisible(true);
            Combat.setVisible(false);
            NextTurn.setVisible(false);
            playerView1.ocultarStealTreasure();
            monsterView1.setVisible(false);
            meet = false;
            combat = false;
            nextTurn = false;
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combatResult = new javax.swing.JLabel();
        MeetTheMonster = new javax.swing.JButton();
        Combat = new javax.swing.JButton();
        NextTurn = new javax.swing.JButton();
        playerView1 = new GUI.PlayerView();
        monsterView1 = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combatResult.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N

        MeetTheMonster.setText("Meet the Monster");
        MeetTheMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeetTheMonsterActionPerformed(evt);
            }
        });

        Combat.setText("Combat");
        Combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombatActionPerformed(evt);
            }
        });

        NextTurn.setText("Next Turn");
        NextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(combatResult)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(MeetTheMonster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Combat)
                        .addGap(18, 18, 18)
                        .addComponent(NextTurn)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeetTheMonster)
                    .addComponent(Combat)
                    .addComponent(NextTurn))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextTurnActionPerformed
        // TODO add your handling code here:
        monsterView1.setVisible(true);
        nextTurn = napakalakiModel.nextTurn();
        if (nextTurn) {
            combatResult.setText(" ");
        }
        setNapakalaki(napakalakiModel);
    }//GEN-LAST:event_NextTurnActionPerformed

    private void MeetTheMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeetTheMonsterActionPerformed
        // TODO add your handling code here:
        meet = true;
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        setNapakalaki(napakalakiModel);
        monsterView1.setVisible(true);
    }//GEN-LAST:event_MeetTheMonsterActionPerformed

    private void CombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombatActionPerformed
        // TODO add your handling code here:
        combat = true;
        combatResult.setText("You " + napakalakiModel.developCombat().toString());
        if (combatResult.getText() == "You WINGAME") {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
            System.exit(1);
        }
        setNapakalaki(napakalakiModel);
        monsterView1.setVisible(true);
    }//GEN-LAST:event_CombatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Combat;
    private javax.swing.JButton MeetTheMonster;
    private javax.swing.JButton NextTurn;
    private javax.swing.JLabel combatResult;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
    private NapakalakiGame.Napakalaki napakalakiModel = null;
    private boolean meet = false;
    private boolean combat = false;
    private boolean nextTurn = false;
}
