/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author nestor
 */
public class PendingBadConsequence extends javax.swing.JPanel {

    /**
     * Creates new form PendingBadConsequence
     */
    public PendingBadConsequence() {
        initComponents();
    }

    public void setPendingBadConsequence(NapakalakiGame.BadConsequence pbc) {
        pendingBadConsequenceModel = pbc;
        if (pbc == null) {
            pendingBadConsequence.setText("");
        } else if (pbc.isEmpty()){
            pendingBadConsequence.setText("El mal rollo pendiente esta vacío.");
        } else{
            pendingBadConsequence.setText(pbc.getText());
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pendingBadConsequence = new javax.swing.JTextArea();

        pendingBadConsequence.setColumns(20);
        pendingBadConsequence.setRows(5);
        jScrollPane1.setViewportView(pendingBadConsequence);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pendingBadConsequence;
    // End of variables declaration//GEN-END:variables
    private NapakalakiGame.BadConsequence pendingBadConsequenceModel = null;
}
