(define (problem Problema4)

(:domain LosMundosDeBelkan)

(:OBJECTS 
    Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Z18 Z19 Z20 Z21 Z22 Z23 Z24 Z25 - zona 
    PROTAGONISTA - protagonista
    OSCAR MANZANA ROSA ALGORITMO ORO ZAPATILLAS BIKINI - objeto
    PRINCESA PRINCIPE BRUJA PROFESOR LEONARDO - personaje
    norte sur este oeste - orientacion
    MOCHILA - mochila
    BOSQUE AGUA PRECIPICIO ARENA PIEDRA - tipo
)

(:INIT
    ; Extremos
    (conectada Z1 Z2 este)
    (conectada Z2 Z1 oeste)
    (conectada Z2 Z3 este)
    (conectada Z2 Z3 oeste)
    (conectada Z3 Z4 este)
    (conectada Z4 Z3 oeste)
    (conectada Z4 Z5 este)
    (conectada Z5 Z6 oeste)

    (conectada Z5 Z10 sur)
    (conectada Z10 Z5 norte)
    (conectada Z10 Z15 sur)
    (conectada Z15 Z10 norte)
    (conectada Z15 Z20 sur)
    (conectada Z20 Z15 norte)
    (conectada Z20 Z25 sur)
    (conectada Z25 Z20 norte)
    
    (conectada Z25 Z24 oeste)
    (conectada Z24 Z25 este)
    (conectada Z24 Z23 oeste)
    (conectada Z23 Z24 este)
    (conectada Z23 Z22 oeste)
    (conectada Z22 Z23 este)
    (conectada Z22 Z21 oeste)
    (conectada Z21 Z22 este)

    (conectada Z21 Z16 norte)
    (conectada Z16 Z21 sur)
    (conectada Z16 Z11 norte)
    (conectada Z11 Z16 sur)
    (conectada Z11 Z6 norte)
    (conectada Z6 Z11 sur)
    (conectada Z6 Z1 norte)
    (conectada Z1 Z6 sur)

    ; Zonas intermedias
    (conectada Z7 Z8 este)
    (conectada Z8 Z7 oeste)
    (conectada Z8 Z3 norte)
    (conectada Z3 Z8 sur)
    (conectada Z13 Z8 norte)
    (conectada Z8 Z13 sur)
    (conectada Z9 Z10 este)
    (conectada Z10 Z9 oeste)
    (conectada Z9 Z14 sur)
    (conectada Z14 Z9 norte)

    (conectada Z11 Z12 este)
    (conectada Z12 Z11 oeste)
    (conectada Z12 Z13 este)
    (conectada Z13 Z12 oeste)
    (conectada Z13 Z14 este)
    (conectada Z14 Z13 oeste)
    (conectada Z17 Z12 norte)
    (conectada Z12 Z17 sur)
    (conectada Z18 Z13 norte)
    (conectada Z13 Z18 sur)
    (conectada Z14 Z19 norte)
    (conectada Z19 Z14 sur)
    
    (conectada Z17 Z18 este)
    (conectada Z18 Z17 oeste)
    (conectada Z19 Z20 este)
    (conectada Z20 Z19 oeste)

    (conectada Z19 Z24 sur)
    (conectada Z24 Z19 norte)

    ; Costes
    (= (distancia Z1 Z2) 1)
    (= (distancia Z2 Z1) 1)
    (= (distancia Z2 Z3) 1)
    (= (distancia Z2 Z3) 1)
    (= (distancia Z3 Z4) 1)
    (= (distancia Z4 Z3) 1)
    (= (distancia Z4 Z5) 1)
    (= (distancia Z5 Z6) 1)
    (= (distancia Z5 Z10) 1)
    (= (distancia Z10 Z5) 1)
    (= (distancia Z10 Z15) 1)
    (= (distancia Z15 Z10) 1)
    (= (distancia Z15 Z20) 1)
    (= (distancia Z20 Z15) 1)
    (= (distancia Z20 Z25) 1)
    (= (distancia Z25 Z20) 1)
    (= (distancia Z25 Z24) 1)
    (= (distancia Z24 Z25) 1)
    (= (distancia Z24 Z23) 1)
    (= (distancia Z23 Z24) 1)
    (= (distancia Z23 Z22) 1)
    (= (distancia Z22 Z23) 1)
    (= (distancia Z22 Z21) 1)
    (= (distancia Z21 Z22) 1)
    (= (distancia Z21 Z16) 1)
    (= (distancia Z16 Z21) 1)
    (= (distancia Z16 Z11) 1)
    (= (distancia Z11 Z16) 1)
    (= (distancia Z11 Z6) 1)
    (= (distancia Z6 Z11) 1)
    (= (distancia Z6 Z1) 1)
    (= (distancia Z1 Z6) 1)
    (= (distancia Z7 Z8) 1)
    (= (distancia Z8 Z7) 1)
    (= (distancia Z8 Z3) 1)
    (= (distancia Z3 Z8) 1)
    (= (distancia Z13 Z8) 1)
    (= (distancia Z8 Z13) 1)
    (= (distancia Z9 Z10) 1)
    (= (distancia Z10 Z9) 1)
    (= (distancia Z9 Z14) 1)
    (= (distancia Z14 Z9) 1)
    (= (distancia Z11 Z12) 1)
    (= (distancia Z12 Z11) 1)
    (= (distancia Z12 Z13) 1)
    (= (distancia Z13 Z12) 1)
    (= (distancia Z13 Z14) 1)
    (= (distancia Z14 Z13) 1)
    (= (distancia Z17 Z12) 1)
    (= (distancia Z12 Z17) 1)
    (= (distancia Z18 Z13) 1)
    (= (distancia Z13 Z18) 1)
    (= (distancia Z14 Z19) 1)
    (= (distancia Z19 Z14) 1)
    (= (distancia Z17 Z18) 1)
    (= (distancia Z18 Z17) 1)
    (= (distancia Z19 Z20) 1)
    (= (distancia Z20 Z19) 1)
    (= (distancia Z19 Z24) 1)
    (= (distancia Z24 Z19) 1)

    ; Tipo de terreno de cada zona
    (tipo_zona Z1 AGUA)
    (tipo_zona Z2 AGUA)
    (tipo_zona Z3 AGUA)
    (tipo_zona Z4 BOSQUE)
    (tipo_zona Z5 BOSQUE)
    (tipo_zona Z6 AGUA)
    (tipo_zona Z7 AGUA)
    (tipo_zona Z8 ARENA)
    (tipo_zona Z9 ARENA)
    (tipo_zona Z10 BOSQUE)
    (tipo_zona Z11 PRECIPICIO)
    (tipo_zona Z12 ARENA)
    (tipo_zona Z13 ARENA)
    (tipo_zona Z14 ARENA)
    (tipo_zona Z15 BOSQUE)
    (tipo_zona Z16 PRECIPICIO)
    (tipo_zona Z17 PRECIPICIO)
    (tipo_zona Z18 PIEDRA)
    (tipo_zona Z19 ARENA)
    (tipo_zona Z20 ARENA)
    (tipo_zona Z21 PIEDRA)
    (tipo_zona Z22 PIEDRA)
    (tipo_zona Z23 PIEDRA)
    (tipo_zona Z24 PIEDRA)
    (tipo_zona Z25 PIEDRA)

    ; Puntos obtenidos
    (= (cantidad_puntos OSCAR LEONARDO) 10)
    (= (cantidad_puntos ROSA LEONARDO) 1)
    (= (cantidad_puntos MANZANA LEONARDO) 3)
    (= (cantidad_puntos ALGORITMO LEONARDO) 4)
    (= (cantidad_puntos ORO LEONARDO) 5)

    (= (cantidad_puntos OSCAR PRINCESA) 5)
    (= (cantidad_puntos ROSA PRINCESA) 10)
    (= (cantidad_puntos MANZANA PRINCESA) 1)
    (= (cantidad_puntos ALGORITMO PRINCESA) 3)
    (= (cantidad_puntos ORO PRINCESA) 4)

    (= (cantidad_puntos OSCAR BRUJA) 4)
    (= (cantidad_puntos ROSA BRUJA) 5)
    (= (cantidad_puntos MANZANA BRUJA) 10)
    (= (cantidad_puntos ALGORITMO BRUJA) 1)
    (= (cantidad_puntos ORO BRUJA) 3)

    (= (cantidad_puntos OSCAR PROFESOR) 3)
    (= (cantidad_puntos ROSA PROFESOR) 4)
    (= (cantidad_puntos MANZANA PROFESOR) 5)
    (= (cantidad_puntos ALGORITMO PROFESOR) 10)
    (= (cantidad_puntos ORO PROFESOR) 1)

    (= (cantidad_puntos OSCAR PRINCIPE) 1)
    (= (cantidad_puntos ROSA PRINCIPE) 3)
    (= (cantidad_puntos MANZANA PRINCIPE) 4)
    (= (cantidad_puntos ALGORITMO PRINCIPE) 5)
    (= (cantidad_puntos ORO PRINCIPE) 10)

    ; Objetos en el mapa
    (esta_obj OSCAR Z22)
    (esta_obj OSCAR Z9)
    (esta_obj OSCAR Z8)
    (esta_obj OSCAR Z12)
    (esta_obj OSCAR Z14)
    (esta_obj OSCAR Z20)
    (esta_obj OSCAR Z23)
    (esta_obj OSCAR Z15)
    (esta_obj OSCAR Z10)
    (esta_obj OSCAR Z19)
    (esta_obj MANZANA Z22)
    (esta_obj MANZANA Z9)
    (esta_obj MANZANA Z8)
    (esta_obj MANZANA Z12)
    (esta_obj MANZANA Z14)
    (esta_obj MANZANA Z20)
    (esta_obj MANZANA Z23)
    (esta_obj MANZANA Z15)
    (esta_obj MANZANA Z10)
    (esta_obj MANZANA Z19)

    (esta_obj BIKINI Z4)
    (esta_obj BIKINI Z20)
    (esta_obj ZAPATILLAS Z7)
    (esta_obj ZAPATILLAS Z8)

    (esta_per PRINCIPE Z6)
    (esta_per LEONARDO Z14)
    (esta_per BRUJA Z5)
    (esta_per PRINCESA Z21)
    (esta_per PROFESOR Z25)
    
    (esta PROTAGONISTA Z13)
    (orien_prota norte)
    (= (coste) 0)
    (= (puntos) 0)
    (manovacia)
    (mochilavacia)

    (util BIKINI AGUA)
    (util ZAPATILLAS BOSQUE)
    (libre PIEDRA)
    (libre ARENA)
)

; El objetivo va a ser entregar los objetos a los personajes
(:goal 
    (and (>= (puntos) 50)))

    (:metric minimize (coste))
)